CREATE TYPE "public"."player_type" AS ENUM('human', 'ai');--> statement-breakpoint
CREATE TYPE "public"."status" AS ENUM('active', 'completed', 'abandoned');--> statement-breakpoint
CREATE TABLE "codenames-leaderboard_game_action" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "codenames-leaderboard_game_action_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"gameId" uuid NOT NULL,
	"playerId" uuid NOT NULL,
	"team" text NOT NULL,
	"action_data" jsonb NOT NULL,
	"timestamp" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "codenames-leaderboard_game" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"status" "status" DEFAULT 'active' NOT NULL,
	"archived" boolean DEFAULT false NOT NULL,
	"game_state" jsonb NOT NULL,
	"winner" varchar(10),
	"startedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"completedAt" timestamp with time zone,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "codenames-leaderboard_player" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"gameId" uuid NOT NULL,
	"team" text NOT NULL,
	"name" varchar(256) NOT NULL,
	"player_type" "player_type" NOT NULL,
	"aiModel" text,
	"withReasoning" boolean,
	"data" jsonb NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "codenames-leaderboard_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "codenames-leaderboard_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "codenames-leaderboard_game_action" ADD CONSTRAINT "codenames-leaderboard_game_action_gameId_codenames-leaderboard_game_id_fk" FOREIGN KEY ("gameId") REFERENCES "public"."codenames-leaderboard_game"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "codenames-leaderboard_game_action" ADD CONSTRAINT "codenames-leaderboard_game_action_playerId_codenames-leaderboard_player_id_fk" FOREIGN KEY ("playerId") REFERENCES "public"."codenames-leaderboard_player"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "codenames-leaderboard_player" ADD CONSTRAINT "codenames-leaderboard_player_gameId_codenames-leaderboard_game_id_fk" FOREIGN KEY ("gameId") REFERENCES "public"."codenames-leaderboard_game"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "game_action_game_idx" ON "codenames-leaderboard_game_action" USING btree ("gameId");--> statement-breakpoint
CREATE INDEX "game_action_timestamp_idx" ON "codenames-leaderboard_game_action" USING btree ("timestamp");--> statement-breakpoint
CREATE INDEX "status_idx" ON "codenames-leaderboard_game" USING btree ("status");--> statement-breakpoint
CREATE INDEX "started_at_idx" ON "codenames-leaderboard_game" USING btree ("startedAt");--> statement-breakpoint
CREATE INDEX "player_type_idx" ON "codenames-leaderboard_player" USING btree ("player_type");--> statement-breakpoint
CREATE INDEX "ai_model_idx" ON "codenames-leaderboard_player" USING btree ("aiModel");--> statement-breakpoint
CREATE INDEX "name_idx" ON "codenames-leaderboard_post" USING btree ("name");